title: TunnelVision
description: "CVE-2024-3661: A local network VPN leaking technique that affects all routing-based VPNs"
show_downloads: true
google_analytics: G-6JTRL0ZRGQ
theme: jekyll-theme-cayman
host: 0.0.0.0
tunnelvision:
  blog_url: https://leviathansecurity.com/blog
  lab_url: https://github.com/leviathansecurity/TunnelVision/

plugins:
  - jekyll-loading-lazy 
  - jekyll-language-plugin